### ISSUE TITLE
REQ/REP hangs when sending messages larger than 1MB

### ISSUE THREAD

**Issue by robsmith11** [blabaere/scaproust#14]
The Req socket hangs when I try to send a message larger than 1MB.  I have the same problem with both IPC and TCP.   Example:

```
extern crate scaproust;

use scaproust::*;

fn recv() {
    loop {
        let mut session = SessionBuilder::new().with("ipc", Ipc).build().unwrap();
        let mut socket = session.create_socket::<Rep>().unwrap();
        socket.bind("ipc:///tmp/s").unwrap();

        println!("Received message of length: {}", socket.recv().unwrap().len());
        socket.send(vec![0]).unwrap();
    }
}

fn send() {
    for n in [1e3,1e4,1e5,0.9e6,1e6,1.1e6].iter() {
        let msg = vec![0;*n as usize];

        let mut session = SessionBuilder::new().with("ipc", Ipc).build().unwrap();
        let mut socket = session.create_socket::<Req>().unwrap();
        socket.connect("ipc:///tmp/s").unwrap();
        socket.send(msg).unwrap();
        socket.recv().unwrap();

        std::thread::sleep(std::time::Duration::from_millis(100));
    }
}

fn main() {
    send();
}
```

**Comment by blabaere** [comment]
Hi,

Each socket has an option to limit the size of incoming messages. The default value for this option is 1 MB. You can change this value using the [RecvMaxSize](https://docs.rs/scaproust/0.3.2/scaproust/enum.ConfigOption.html) variant.

```rust
socket.set_option(ConfigOption::RecvMaxSize(64 * 1024));
```

Regards,
Benoît

**Comment by robsmith11** [comment]
Ah.. I didn't even think to look for an option like that.  Thanks, that fixes it.

Is it not possible/desirable for the sending socket to return an error when the receiving socket's limit is exceeded rather than hang?

**Comment by robsmith11** [comment]
Looks like I spoke too soon without actually testing it..

RecvMaxSize isn't marked as a generic socket option, so it just returns an error when trying to set.  This fixes it:
```
diff --git a/src/core/config.rs b/src/core/config.rs
index 3bf7806..c4feefc 100644
--- a/src/core/config.rs
+++ b/src/core/config.rs
@@ -118,6 +118,7 @@ impl ConfigOption {
             ConfigOption::Linger(_)       |
             ConfigOption::SendTimeout(_)  |
             ConfigOption::SendPriority(_) |
+            ConfigOption::RecvMaxSize(_)  |
             ConfigOption::RecvTimeout(_)  |
             ConfigOption::RecvPriority(_) |
             ConfigOption::RetryIvl(_)     |
```

The documentation is also incorrect.  Setting the max size to `0` doesn't remove the limit.

**Comment by polarathene** [comment]
Yep, just ran into the same problem(I had tried the option from the docs before seeing the message and coudln't figure out why it was considered invalid). Error message:

```
Custom { kind: InvalidInput, error: StringError("option not supported") }',
```

**Comment by blabaere** [comment]
@robsmith11 @polarathene 
Looks like I'm the one who spoke too fast without having the proper test(s) in place.
I fixed the option setter so that `ConfigOption::RecvMaxSize` is supported.
I also fixed the tcp and ipc transports to make a zero value behave as advertised.
Thanks for reporting these !

**Comment by blabaere** [comment]
Regarding the sending socket behavior in the case the receiving socket chooses to discard the message, the correct behavior would be to have the receiver not only drop the message but also close the connection. This should prevent the sender from hanging. I will investigate this later on.

**Comment by blabaere** [comment]
The problem with REQ/REP is that REQ will retry to send periodically, and as soon as the automatic reconnection occurs.
