### ISSUE TITLE
Clippy is a hard dependency, therefore scaproust can't be built on beta channel

### ISSUE THREAD

**Issue by klardotsh** [blabaere/scaproust#4]
Clippy is also broken on nightly right now, meaning there is just no way to use scaproust at all.

Readme at https://github.com/Manishearth/rust-clippy recommends adding clippy as an optional dependency.

**Comment by klardotsh** [comment]
Update: clippy 104 seems to build here (I tried `cargo install clippy` with rustup default set to nightly) so maybe a version bump is in order to make scaproust build on nightly, at least?

**Comment by blabaere** [comment]
Clippy dependency version was updated to 0.0.104 on december 18, so it should build out of the box right now. It's true it was broken during a few days but this is quite unusual. Since using it as a compiler plugin is not the recommended way I'll remove this constraint.
